-- FlemiCoach - schéma initial Supabase
-- À exécuter dans Supabase SQL Editor sur un projet neuf.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  full_name text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.teams (
  id uuid primary key default gen_random_uuid(),
  created_by uuid not null references auth.users(id) on delete cascade,
  name text not null check (char_length(name) between 1 and 80),
  season_start date not null,
  season_end date not null,
  email_reminders boolean not null default true,
  training_reminder_hours integer not null default 24 check (training_reminder_hours between 1 and 168),
  match_reminder_hours integer not null default 48 check (match_reminder_hours between 1 and 336),
  timezone text not null default 'Europe/Paris',
  created_at timestamptz not null default now(),
  check (season_end >= season_start)
);

create table if not exists public.team_members (
  team_id uuid not null references public.teams(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'coach' check (role in ('owner','coach')),
  created_at timestamptz not null default now(),
  primary key (team_id, user_id)
);

create table if not exists public.training_rules (
  id uuid primary key default gen_random_uuid(),
  team_id uuid not null references public.teams(id) on delete cascade,
  weekday smallint not null check (weekday between 0 and 6),
  start_time time not null,
  end_time time not null,
  created_at timestamptz not null default now(),
  check (end_time > start_time)
);

create table if not exists public.players (
  id uuid primary key default gen_random_uuid(),
  team_id uuid not null references public.teams(id) on delete cascade,
  name text not null check (char_length(name) between 1 and 120),
  active boolean not null default true,
  created_at timestamptz not null default now()
);
create index if not exists players_team_id_idx on public.players(team_id);

create table if not exists public.events (
  id uuid primary key default gen_random_uuid(),
  team_id uuid not null references public.teams(id) on delete cascade,
  type text not null check (type in ('training','match','event')),
  title text not null check (char_length(title) between 1 and 160),
  event_date date not null,
  start_time time not null,
  end_time time,
  location text not null default '',
  generated boolean not null default false,
  public_token uuid not null default gen_random_uuid() unique,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);
create index if not exists events_team_date_idx on public.events(team_id, event_date, start_time);
create index if not exists events_public_token_idx on public.events(public_token);

create table if not exists public.attendance (
  event_id uuid not null references public.events(id) on delete cascade,
  player_id uuid not null references public.players(id) on delete cascade,
  declared_status text not null default 'NO_REPLY' check (declared_status in ('NO_REPLY','PRESENT','ABSENT')),
  actual_status text check (actual_status is null or actual_status in ('PRESENT','ABSENT')),
  note text not null default '' check (char_length(note) <= 500),
  declared_at timestamptz,
  actual_at timestamptz,
  updated_at timestamptz not null default now(),
  primary key (event_id, player_id)
);
create index if not exists attendance_player_idx on public.attendance(player_id);

create table if not exists public.reminder_log (
  id bigint generated by default as identity primary key,
  event_id uuid not null references public.events(id) on delete cascade,
  recipient text not null,
  reminder_kind text not null check (reminder_kind in ('training','match')),
  sent_at timestamptz not null default now(),
  unique(event_id, recipient, reminder_kind)
);

-- Profil automatique à l'inscription
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles(id, email, full_name)
  values (new.id, coalesce(new.email,''), coalesce(new.raw_user_meta_data->>'full_name',''))
  on conflict (id) do update set email = excluded.email;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert or update of email on auth.users
for each row execute procedure public.handle_new_user();

-- Helpers d'autorisation (SECURITY DEFINER pour éviter la récursion RLS)
create or replace function public.is_team_member(p_team_id uuid)
returns boolean
language sql
stable
security definer set search_path = public
as $$
  select exists (
    select 1 from public.team_members tm
    where tm.team_id = p_team_id and tm.user_id = auth.uid()
  );
$$;

create or replace function public.is_team_owner(p_team_id uuid)
returns boolean
language sql
stable
security definer set search_path = public
as $$
  select exists (
    select 1 from public.team_members tm
    where tm.team_id = p_team_id and tm.user_id = auth.uid() and tm.role = 'owner'
  ) or exists (
    select 1 from public.teams t
    where t.id = p_team_id and t.created_by = auth.uid()
  );
$$;

revoke all on function public.is_team_member(uuid) from public;
revoke all on function public.is_team_owner(uuid) from public;
grant execute on function public.is_team_member(uuid) to authenticated;
grant execute on function public.is_team_owner(uuid) to authenticated;

-- Planning : régénère uniquement les séances futures générées automatiquement.
create or replace function public.regenerate_training_events(p_team_id uuid)
returns integer
language plpgsql
security definer set search_path = public
as $$
declare
  t public.teams%rowtype;
  inserted_count integer := 0;
  r record;
  d date;
begin
  if auth.uid() is null or not public.is_team_member(p_team_id) then
    raise exception 'not authorized';
  end if;

  select * into t from public.teams where id = p_team_id;
  if not found then raise exception 'team not found'; end if;

  delete from public.events e
  where e.team_id = p_team_id
    and e.generated = true
    and e.event_date >= current_date
    and not exists (select 1 from public.attendance a where a.event_id = e.id);

  for r in select * from public.training_rules where team_id = p_team_id loop
    d := greatest(t.season_start, current_date);
    while d <= t.season_end loop
      if extract(dow from d)::int = r.weekday then
        if not exists (
          select 1 from public.events e
          where e.team_id = p_team_id and e.type='training' and e.event_date=d and e.start_time=r.start_time
        ) then
          insert into public.events(team_id,type,title,event_date,start_time,end_time,location,generated,created_by)
          values(p_team_id,'training','Entraînement',d,r.start_time,r.end_time,'',true,auth.uid());
          inserted_count := inserted_count + 1;
        end if;
      end if;
      d := d + 1;
    end loop;
  end loop;

  return inserted_count;
end;
$$;
revoke all on function public.regenerate_training_events(uuid) from public;
grant execute on function public.regenerate_training_events(uuid) to authenticated;


-- Événements dont le rappel doit partir maintenant. Le calcul est fait en base
-- pour respecter le fuseau horaire de l'équipe, y compris heure d'été/hiver.
create or replace function public.get_due_reminder_events()
returns table(
  event_id uuid,
  team_id uuid,
  event_type text,
  title text,
  event_date date,
  start_time time,
  location text,
  public_token uuid,
  team_name text,
  reminder_kind text
)
language sql
stable
security definer set search_path = public
as $$
  select
    e.id,
    e.team_id,
    e.type,
    e.title,
    e.event_date,
    e.start_time,
    e.location,
    e.public_token,
    t.name,
    case when e.type='match' then 'match' else 'training' end
  from public.events e
  join public.teams t on t.id=e.team_id
  where t.email_reminders=true
    and e.type in ('training','match')
    and (((e.event_date + e.start_time) at time zone t.timezone) > now())
    and abs(
      extract(epoch from (((e.event_date + e.start_time) at time zone t.timezone) - now())) / 3600.0
      - case when e.type='match' then t.match_reminder_hours else t.training_reminder_hours end
    ) <= 0.75;
$$;
revoke all on function public.get_due_reminder_events() from public;
grant execute on function public.get_due_reminder_events() to service_role;

-- Page publique parent. Le token de l'événement est le secret du lien.
create or replace function public.get_public_event(p_token uuid)
returns jsonb
language sql
stable
security definer set search_path = public
as $$
  select jsonb_build_object(
    'event', jsonb_build_object(
      'id', e.id,
      'team_name', t.name,
      'type', e.type,
      'title', e.title,
      'event_date', e.event_date,
      'start_time', e.start_time,
      'location', e.location
    ),
    'players', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', p.id,
        'name', p.name,
        'status', coalesce(a.declared_status,'NO_REPLY')
      ) order by p.name)
      from public.players p
      left join public.attendance a on a.event_id=e.id and a.player_id=p.id
      where p.team_id=e.team_id and p.active=true
    ), '[]'::jsonb)
  )
  from public.events e
  join public.teams t on t.id=e.team_id
  where e.public_token=p_token
    and e.event_date >= current_date - 1
    and e.event_date <= current_date + 60;
$$;

create or replace function public.submit_public_attendance(
  p_token uuid,
  p_player_id uuid,
  p_status text,
  p_note text default ''
)
returns boolean
language plpgsql
security definer set search_path = public
as $$
declare
  e public.events%rowtype;
begin
  if p_status not in ('PRESENT','ABSENT') then raise exception 'invalid status'; end if;
  if char_length(coalesce(p_note,'')) > 500 then raise exception 'note too long'; end if;

  select * into e from public.events
  where public_token=p_token and event_date >= current_date - 1 and event_date <= current_date + 60;
  if not found then raise exception 'event unavailable'; end if;

  if not exists(select 1 from public.players where id=p_player_id and team_id=e.team_id and active=true) then
    raise exception 'invalid player';
  end if;

  insert into public.attendance(event_id,player_id,declared_status,note,declared_at,updated_at)
  values(e.id,p_player_id,p_status,coalesce(p_note,''),now(),now())
  on conflict(event_id,player_id) do update set
    declared_status=excluded.declared_status,
    note=excluded.note,
    declared_at=now(),
    updated_at=now();
  return true;
end;
$$;

revoke all on function public.get_public_event(uuid) from public;
revoke all on function public.submit_public_attendance(uuid,uuid,text,text) from public;
grant execute on function public.get_public_event(uuid) to anon, authenticated;
grant execute on function public.submit_public_attendance(uuid,uuid,text,text) to anon, authenticated;

-- RLS
alter table public.profiles enable row level security;
alter table public.teams enable row level security;
alter table public.team_members enable row level security;
alter table public.training_rules enable row level security;
alter table public.players enable row level security;
alter table public.events enable row level security;
alter table public.attendance enable row level security;
alter table public.reminder_log enable row level security;

-- Retire les privilèges implicites puis réaccorde le strict nécessaire.
revoke all on table public.profiles, public.teams, public.team_members, public.training_rules, public.players, public.events, public.attendance, public.reminder_log from anon, authenticated;
grant select, update on public.profiles to authenticated;
grant select, insert, update, delete on public.teams, public.team_members, public.training_rules, public.players, public.events, public.attendance to authenticated;
-- Aucun accès direct anonyme aux tables. Les parents passent exclusivement par RPC.

create policy profiles_select_self on public.profiles for select to authenticated using (id = auth.uid());
create policy profiles_update_self on public.profiles for update to authenticated using (id = auth.uid()) with check (id = auth.uid());

create policy teams_select_member on public.teams for select to authenticated using (created_by=auth.uid() or public.is_team_member(id));
create policy teams_insert_self on public.teams for insert to authenticated with check (created_by=auth.uid());
create policy teams_update_member on public.teams for update to authenticated using (created_by=auth.uid() or public.is_team_member(id)) with check (created_by=auth.uid() or public.is_team_member(id));
create policy teams_delete_owner on public.teams for delete to authenticated using (public.is_team_owner(id));

create policy members_select_team on public.team_members for select to authenticated using (user_id=auth.uid() or public.is_team_member(team_id));
create policy members_insert_owner on public.team_members for insert to authenticated with check (
  (user_id=auth.uid() and exists(select 1 from public.teams t where t.id=team_id and t.created_by=auth.uid()))
  or public.is_team_owner(team_id)
);
create policy members_update_owner on public.team_members for update to authenticated using (public.is_team_owner(team_id)) with check (public.is_team_owner(team_id));
create policy members_delete_owner on public.team_members for delete to authenticated using (public.is_team_owner(team_id));

create policy rules_all_member_select on public.training_rules for select to authenticated using (public.is_team_member(team_id));
create policy rules_all_member_insert on public.training_rules for insert to authenticated with check (public.is_team_member(team_id));
create policy rules_all_member_update on public.training_rules for update to authenticated using (public.is_team_member(team_id)) with check (public.is_team_member(team_id));
create policy rules_all_member_delete on public.training_rules for delete to authenticated using (public.is_team_member(team_id));

create policy players_select_member on public.players for select to authenticated using (public.is_team_member(team_id));
create policy players_insert_member on public.players for insert to authenticated with check (public.is_team_member(team_id));
create policy players_update_member on public.players for update to authenticated using (public.is_team_member(team_id)) with check (public.is_team_member(team_id));
create policy players_delete_member on public.players for delete to authenticated using (public.is_team_member(team_id));

create policy events_select_member on public.events for select to authenticated using (public.is_team_member(team_id));
create policy events_insert_member on public.events for insert to authenticated with check (public.is_team_member(team_id));
create policy events_update_member on public.events for update to authenticated using (public.is_team_member(team_id)) with check (public.is_team_member(team_id));
create policy events_delete_member on public.events for delete to authenticated using (public.is_team_member(team_id));

create policy attendance_select_member on public.attendance for select to authenticated using (
  exists(select 1 from public.events e where e.id=event_id and public.is_team_member(e.team_id))
);
create policy attendance_insert_member on public.attendance for insert to authenticated with check (
  exists(select 1 from public.events e where e.id=event_id and public.is_team_member(e.team_id))
  and exists(select 1 from public.players p join public.events e on e.id = public.attendance.event_id where p.id = public.attendance.player_id and p.team_id=e.team_id)
);
create policy attendance_update_member on public.attendance for update to authenticated using (
  exists(select 1 from public.events e where e.id=event_id and public.is_team_member(e.team_id))
) with check (
  exists(select 1 from public.events e where e.id=event_id and public.is_team_member(e.team_id))
);
create policy attendance_delete_member on public.attendance for delete to authenticated using (
  exists(select 1 from public.events e where e.id=event_id and public.is_team_member(e.team_id))
);

-- reminder_log n'est accessible qu'au service secret depuis l'Edge Function.
-- service_role / secret key bypass RLS.
