-- FlemiCoach - retours utilisateurs depuis l'espace coach

create table if not exists public.user_feedback (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  team_id uuid references public.teams(id) on delete set null,
  message text not null check (char_length(trim(message)) between 3 and 1500),
  created_at timestamptz not null default now()
);

create index if not exists user_feedback_user_id_idx on public.user_feedback(user_id);
create index if not exists user_feedback_created_at_idx on public.user_feedback(created_at desc);

alter table public.user_feedback enable row level security;

revoke all on table public.user_feedback from anon, authenticated;
grant insert on table public.user_feedback to authenticated;

create policy user_feedback_insert_self
on public.user_feedback
for insert
to authenticated
with check (
  user_id = auth.uid()
  and (team_id is null or public.is_team_member(team_id))
);
